# Generated by Django 5.2.6 on 2025-09-25 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=140)),
                ('price_for_a_night', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.rooms')),
            ],
        ),
    ]
