# Generated by Django 5.2.6 on 2025-09-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_rooms_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
