# Generated by Django 5.2.6 on 2025-09-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_rename_room_id_roomreservation_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='room',
            new_name='room_id',
        ),
    ]
