# Generated by Django 5.2.6 on 2025-09-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_room_roomreservation_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
